### ISSUE TITLE
Telegram Notification

### ISSUE THREAD

**Issue by flemzord** [gomodules/notify#17]
Hello, 

it's possible create a telegram notification ? 

Maxence

**Comment by tamalsaha** [comment]
We have not added Telegram integration. But you can add one by implementing `ByChat` interface. https://github.com/appscode/go-notify/blob/master/types.go#L23

We are happy to add it if you send us a pr.

**Comment by tamalsaha** [comment]
Telegram Bot API:
- https://github.com/python-telegram-bot/python-telegram-bot/wiki/Introduction-to-the-API
- https://core.telegram.org/bots/api#available-methods
- https://core.telegram.org/bots/api#authorizing-your-bot

https://github.com/kimrgrey/go-telegram
