### ISSUE TITLE
Enable Hipchat Notification options: Colour and Notify

### ISSUE THREAD

**Issue by jorgepi** [gomodules/notify#27]
I'm testing appscode/kubed app to send notifications to Hipchat coming from my kubernetes cluster. It would be great if we could configure the hipchat notification colour (For example: Green for CREATE operations and Red for DELETE operations) and notification type.

I'm very amateur with golang but I think it would be possible to define a new variable for the colour and set the value according to the operation type and something similar for the notification type with a default value in case it is not defined.

Then we could replace this line:

`_, err := h.Room.Notification(room, &hipchat.NotificationRequest{Message: c.body})`

with this one:

`_, err := h.Room.Notification(room, &hipchat.NotificationRequest{Message: c.body, Color: c.colour, Notify: c.notify})`

**Comment by Constantin07** [comment]
I'm facing the same issue - it would be nice to have an option to specify the colour and notify.

**Comment by tamalsaha** [comment]
I added the support to this library. Now, we need to vendor this in kubed and use this .

**Comment by tamalsaha** [comment]
in pr #28

**Comment by jorgepi** [comment]
Thanks @tamalsaha for your quick fix
